export enum ActionEffectType {
  OBTAIN_RESOURCE,
  DISCARD_RESOURCE,
  PLOW_FIELD,
  SOW,
  PLAY_OCCUPATION_CARD,
  BECOME_FIRST_PLAYER,
  MAKE_A_CHILD,
  BUILD_ROOMS,
  RENOVATE_HOUSE,
  PLACE_FENCES,
  BUILD_STABLES,
}
